### PR TITLE
Expanding HTTPS documentation

### PR DESCRIPTION
**Pull request by maderikra**

### CODE REVIEW

**Comment by trevorthornton** [comment]
This looks good, but I wonder if we want to include the old Step 1 (restrict access to application urls) at the end as an FYI. I think we said it wasn't necessary but couldn't hurt to include it as an option.

**Comment by maderikra** [comment]
Good point, perhaps link to the relevant section elsewhere in the documentation? I guess it would [be this](https://github.com/archivesspace/tech-docs/blob/master/administration/getting_started.md#start-archivesspace)?

**Comment by trevorthornton** [comment]
It's actually the second part of the original step 1 that I'm thinking about (the iptables bit). If you want to use https://staff.myarchive.org for the front end, you probably don't want to keep http://myarchive.org:8080 open, but you do want to keep all those ports open on localhost so the components can talk to each other.

**Comment by maderikra** [comment]
Closing pull request, will re-open with expanded documentation on setting up subdomains

**Pull request closed without merging**
